export const data = [
  {
    id: '123456',
    chosenCompany: 'Company A',
    chosenProduct: 'Product A',
    chosenDate: '2019-10-2',
    price: '12.45',
    quantity: '12',
    remarks: 'Undefined',
    terms: 'Undefined',
    status: 'Pending',
    urgency: 'Yes',
    created_at: '2019-10-4',
    updated_at: '2019-10-3',
    type: 'Open',
    histories: [],
  },
  {
    id: '123456',
    chosenCompany: 'Company B',
    chosenProduct: 'Product A',
    chosenDate: '2019-10-2',
    price: '12.45',
    quantity: '12',
    remarks: 'Undefined',
    terms: 'Undefined',
    status: 'Processing',
    urgency: 'Yes',
    created_at: '2019-10-4',
    updated_at: '2019-10-3',
    type: 'Open',
  },
  {
    id: '123456',
    chosenCompany: 'Company C',
    chosenProduct: 'Product D',
    chosenDate: '2019-10-2',
    price: '12.45',
    quantity: '12',
    remarks: 'Undefined',
    terms: 'Undefined',
    status: 'Out-For-Delivery',
    urgency: 'Yes',
    created_at: '2019-10-4',
    updated_at: '2019-10-3',
    type: 'Open',
  },
  {
    id: '123456',
    chosenCompany: 'Company D',
    chosenProduct: 'Product A',
    chosenDate: '2019-10-2',
    price: '12.45',
    quantity: '12',
    remarks: 'Undefined',
    terms: 'Undefined',
    status: 'On-Hold',
    urgency: 'Yes',
    created_at: '2019-10-4',
    updated_at: '2019-10-3',
    type: 'Open',
  },
  {
    id: '123456',
    chosenCompany: 'Company A',
    chosenProduct: 'Product C',
    chosenDate: '2019-10-2',
    price: '12.45',
    quantity: '12',
    remarks: 'Undefined',
    terms: 'Undefined',
    status: 'Rejected',
    urgency: 'Yes',
    created_at: '2019-10-4',
    updated_at: '2019-10-3',
    type: 'Closed',
  },
  {
    id: '123456',
    chosenCompany: 'Company A',
    chosenProduct: 'Product A',
    chosenDate: '2019-10-2',
    price: '12.45',
    quantity: '12',
    remarks: 'Undefined',
    terms: 'Undefined',
    status: 'Delivered',
    urgency: 'Yes',
    created_at: '2019-10-4',
    updated_at: '2019-10-3',
    type: 'Closed',
  },
  {
    id: '123456',
    chosenCompany: 'Company A',
    chosenProduct: 'Product A',
    chosenDate: '2019-10-2',
    price: '12.45',
    quantity: '12',
    remarks: 'Undefined',
    terms: 'Undefined',
    status: 'Canceled',
    urgency: 'Yes',
    created_at: '2019-10-4',
    updated_at: '2019-10-3',
    type: 'Closed',
  },
]
